### ISSUE TITLE
Предложение по экспорту в Latex 

### ISSUE THREAD

**Issue by SugarHedgehog** [nickkolok/chas-ege#1024]
Делить варианты на отдельные tex файлы

**Comment by SugarHedgehog** [comment]
f0e26f11d6438f31ef9ccb92b94d188c705777de

**Comment by SugarHedgehog** [comment]
Нужна кнопка "все варианты в одном файле"

**Comment by SugarHedgehog** [comment]
И кнопка "ответы после всех вариантов/после каждого"

**Comment by nickkolok** [comment]
Это должна быть кнопка, нажимаемая уже после генерации?

**Comment by SugarHedgehog** [comment]
> Это должна быть кнопка, нажимаемая уже после генерации?

На ваше усмотрение
Должно же отражаться только на latex экспортации

**Comment by SugarHedgehog** [comment]
Решено локальными конфигурациями
