### ISSUE TITLE
Модификатор .allDecimalsToStandard()

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1193]
Чтобы не мучиться

**Comment by SugarHedgehog** [comment]
Что оно должно делать?

**Comment by nickkolok** [comment]
Сейчас есть риск забыть написать .ts()
А есть у нас, ЕМНИП, одноимённая функция - String.prototype.allDecimalsToStandard()

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/pull/1302
