### ISSUE TITLE
Тестирование шаблонов по тригонометрии

### ISSUE THREAD

**Issue by Aisse-258** [nickkolok/chas-ege#1248]
@SugarHedgehog: Точно известно, что кривой 12/15.js
А также возможны ошибки: в 4,5,6,7, 12,13,14,16,17,38
Так же желательно проштрудировать остальные 12номера ЕГЭ и по возможности объединить некоторые
Пример:
21,22,23
Выражение идентично, но зачем-то разбито

Задача: проверить перечисленные шаблоны на ошибки. Те, что сбойные - отключить из main.js и fipi.js.

**Comment by Aisse-258** [comment]
4,5,6 проверены , ошибок нет

**Comment by Aisse-258** [comment]
некоторые задачи в этой категории могут выглядеть одинаково, но решаться по-разному в зависимости от того, есть ли у функций экстремумы на отрезке

**Comment by Aisse-258** [comment]
Особенности проверенных шаблонов + косяки
4 - ответ всегда в нуле (нет экстремума), только sin|cos
5 - на одном из концов отрезка (нет экстремума),  только sin|cos
6 - ответ всегда в нуле, равен прибавляемой константе, только tan
7 -  только tan на (-п/4;п/4) есть косяк:
![image](https://github.com/nickkolok/chas-ege/assets/50519492/c335539d-e303-42d1-8f43-1e2c3b9b7ce0)
12 - есть 1 экстремум в точке п/3, ответ всегда там. только cos, целые ответы
есть несокращенные множители:
![image](https://github.com/nickkolok/chas-ege/assets/50519492/0befbcfb-e079-4aba-8ada-ddf1fc678f99)
13 - есть 1 экстремум в точке п/3, ответ всегда там. только cos, есть дробные ответы

**Comment by nickkolok** [comment]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/b07f5059-e236-490d-a337-bf0c0c700fb5)

Ноль тут, конечно, лишний. Это, конечно, баг, достойный суйни. То, что ответ всегда там - скорее всего, не баг, а фича прототипа.

Пока поводов для отключения не вижу! Как я понимаю, математически неверных утверждений ведь тут нет?

**Comment by Aisse-258** [comment]
математически утверждения правильные, но с оформлением есть такой косяк

**Comment by nickkolok** [comment]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/c79930a9-0941-4465-95b0-3873386ecadb)

**Comment by nickkolok** [comment]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/4aa7a848-fb8c-4402-90d0-9a5089dfde0e)

**Comment by Aisse-258** [comment]
14 - только cos, 1 экстремум на отрезке в т п/4, ответ всегда там - правильно

**Comment by nickkolok** [comment]
16.js - экстремум всегда в $\pi/4$, она может быть краем, а может не быть. Смотрится ОК.
![image](https://github.com/nickkolok/chas-ege/assets/5008131/3298d8a4-1b0e-4393-aeb1-02d4a1bc29ec)

**Comment by Aisse-258** [comment]
![image](https://github.com/nickkolok/chas-ege/assets/50519492/1059512c-9c94-40a5-9cc2-364f99dedfaf)

**Comment by Aisse-258** [comment]
ответ тоже кривой
![image](https://github.com/nickkolok/chas-ege/assets/50519492/87e7385f-8f4c-441a-8f97-53552e6310d6)

**Comment by nickkolok** [comment]
Кажется, ноль заборол!
![image](https://github.com/nickkolok/chas-ege/assets/5008131/f8953799-8e51-4096-94fc-f51e34b27341)

**Comment by Aisse-258** [comment]
21, 22, 23 - отличаются постоянными знаками констант
21 - х в показателе степени всегда с плюсом, знаки перед константами в степени и в скобке всегда разные
![image](https://github.com/nickkolok/chas-ege/assets/50519492/9be28973-6439-4b06-bf4e-84d1d1c035c6)
22 - х в показателе степени всегда с минусом, скобка и показатель всегда одинаковые
![image](https://github.com/nickkolok/chas-ege/assets/50519492/6f0bf60d-b436-48f6-a5ad-894671f0af86)
23 - х в показателе всегда с минусом, в скобке всегда с плюсом, знаки констант одинаковые
![image](https://github.com/nickkolok/chas-ege/assets/50519492/badf7e3e-19ff-473f-9c01-c237a715b46c)

шаблоны написаны старым кодом, поэтому объединять их как есть будет затруднительно
лучше оставить как есть, либо написать новый шаблон, который покроет все 3

**Comment by nickkolok** [comment]
А вроде тут всё. В любом случае, принято решение старые шаблоны - в архив, сбойные обнаруженные  - отключить, а ФИПИ делать на новом движке.
@SugarHedgehog , есть ли возражения против закрытия?

**Comment by SugarHedgehog** [comment]
Двумя руками за!
