### ISSUE TITLE
Раскрасить графики в цвета Час ЕГЭ

### ISSUE THREAD

**Issue by SugarHedgehog** [nickkolok/chas-ege#1255]
@Aisse-258 
Просьба, окрасить графики(производные и графики функций) в "брендовые цвета"
Они же `om.primaryBrandColors`, `om.secondaryBrandColors`

**Comment by nickkolok** [comment]
Насколько я понимаю, @SugarHedgehog , сейчас это сделано по умолчанию? Каким пуллреквестом, если не сложно его указать?

**Comment by SugarHedgehog** [comment]
> Насколько я понимаю, @SugarHedgehog , сейчас это сделано по умолчанию? Каким пуллреквестом, если не сложно его указать?

Ещё не сделано
Пока я в раздумьях

**Comment by SugarHedgehog** [comment]
Оказалось неудачным решением. Тк красится то, что не следует.
