### ISSUE TITLE
Дефицитная "девятка" про обогрев помещения

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1273]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/5ab25834-0ad9-4441-a7d5-a9ae1697ee91)

https://www.time4math.ru/_files/ugd/3fbc02_4f643ee5f7ba4d2fb3bb234ba2eab164.pdf

Смысл тот же, что и в #1247

Теплоёмкость воды менять не надо :)

**Comment by Aisse-258** [comment]
Аналог на РешуЕГЭ
https://math-ege.sdamgia.ru/problem?id=27995

**Comment by Aisse-258** [comment]
![image](https://github.com/nickkolok/chas-ege/assets/50519492/7631c058-95a2-48ff-a817-d08d59bf6e0a)
![image](https://github.com/nickkolok/chas-ege/assets/50519492/405a42bf-e79f-433d-ba5d-467947f99ddc)
![image](https://github.com/nickkolok/chas-ege/assets/50519492/bccc3aa9-fe24-4baf-9a9e-3bf0b095f375)

**Comment by Aisse-258** [comment]
![image](https://github.com/nickkolok/chas-ege/assets/50519492/12d2689b-104f-4cbc-9427-56099beb7142)
