### ISSUE TITLE
Дефицитная девятка про мячик и косинус

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1275]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/b7bfd1dd-809f-4202-9a03-8234af1fdc77)
https://www.time4math.ru/_files/ugd/3fbc02_4f643ee5f7ba4d2fb3bb234ba2eab164.pdf
Аналогично #1247
Очевидно, что тут сначала генерится угол $\alpha$ (из не такого уж и богатого списка значений, при которых косинус рациональный и не обращается в ноль). $g$ варьировать не надо. Высоту над стенкой - пожалуй, стОит. Вообще задача слабовариативная. Разве что с обозначением угла поиграться...

**Comment by Aisse-258** [comment]
в работе
