### ISSUE TITLE
Разобраться с девяткой про мяч, летящий под углом

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1298]
Есть у нас вот такой шаблон: zdn/matege2023p/8/11.js

![image](https://github.com/nickkolok/chas-ege/assets/5008131/46d2b84c-fc70-4ec3-a2ff-cfa9856b535f)

В списках ФИПИ написано вот так:
![image](https://github.com/nickkolok/chas-ege/assets/5008131/b69c94d8-5cc6-46ec-a9c0-2499f303c66a)

Возникает закономерный вопрос: что, собственно, происходит? Там что, ответ всегда одинаковый (типа 30 градусов)? И как с этим быть?..

**Comment by Aisse-258** [comment]
похоже что шаблон кривой
![image](https://github.com/nickkolok/chas-ege/assets/50519492/bf0df167-25a9-4509-9596-467e3b13f6c7)
