### ISSUE TITLE
План на текстовые

### ISSUE THREAD

**Issue by SugarHedgehog** [nickkolok/chas-ege#1303]
Проценты 

- [x] 39 https://github.com/nickkolok/chas-ege/pull/1304
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/e38bc577-80a5-415f-a10b-c3b664f9c11b)

**Comment by SugarHedgehog** [comment]
- [x] 33 https://github.com/nickkolok/chas-ege/pull/1306
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/fa624b57-6196-4902-9777-05383a08a3e0)

**Comment by SugarHedgehog** [comment]
- [x] 55

![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/429861bf-e8f5-4a25-a331-f0622b37a78a)
0e9a70468e6217b2fb963f454a92640e19a7ac05

**Comment by SugarHedgehog** [comment]
- [x] 60 https://github.com/nickkolok/chas-ege/pull/1309
- [x] 63 https://github.com/nickkolok/chas-ege/pull/1310
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/1ee92a21-bce9-44b2-894a-ba3eabd58342)

**Comment by SugarHedgehog** [comment]
- [x] 67
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/12164dd5-84cb-48d0-9c80-19b28e350bb3)

**Comment by SugarHedgehog** [comment]
- [x] 71 https://github.com/nickkolok/chas-ege/pull/1562
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/1056c518-9f97-4346-907e-46ea16f4c24a)

**Comment by SugarHedgehog** [comment]
- [x] 75
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/709ae20f-6d82-456d-8ba2-00d066239766)
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/097627cd-fa04-426e-af69-84822a7f5cf0)

**Comment by SugarHedgehog** [comment]
- [x] 83
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/8f46a430-72b6-4aba-af4c-578e88c7bb11)

**Comment by SugarHedgehog** [comment]
- [x] 87
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/ffc9a742-5059-4113-826e-c39f22a87ee5)

**Comment by SugarHedgehog** [comment]
- [x] 93
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/c4a6dfea-2708-4a92-b802-50c9e283dfda)

**Comment by SugarHedgehog** [comment]
- [x] 97
https://github.com/nickkolok/chas-ege/pull/1520
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/21582622-ebf4-4145-89ab-cd2457c926ce)

**Comment by SugarHedgehog** [comment]
- [x] 103

![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/396da1a5-1462-40c8-9961-728393fa51a9)

**Comment by SugarHedgehog** [comment]
- [ ] 107
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/0823a2ff-dff9-4e6b-891e-aeafe647ccbd)

**Comment by SugarHedgehog** [comment]
- [ ] 111

![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/1366a981-cd21-4e87-99c9-0c0236bfd909)

**Comment by SugarHedgehog** [comment]
- [ ] 115
https://github.com/nickkolok/chas-ege/issues/1544
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/8f4e7774-c3e3-43a5-9859-2e6e05aeff47)

**Comment by SugarHedgehog** [comment]
- [ ] 119
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/289a93a3-11af-43f6-92c6-d1ceb2cb6798)

**Comment by SugarHedgehog** [comment]
- [ ] 121
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/55471f22-7161-456b-b9c6-2b6f57623d00)

**Comment by SugarHedgehog** [comment]
- [ ] 123
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/07e93fd4-66e3-432e-90d3-3e7a5f5bbd7a)

**Comment by SugarHedgehog** [comment]
- [ ] 125

![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/591e0226-2242-4e18-96cf-74a2b392e312)

**Comment by SugarHedgehog** [comment]
- [ ] 129
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/d001d169-204c-42b1-a060-2792be843b78)

**Comment by SugarHedgehog** [comment]
- [ ] 133
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/bbce8df7-29f0-470f-a6b7-0dab18f0fad9)

**Comment by SugarHedgehog** [comment]
- [ ] 137
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/31af5360-a588-4a9d-8cc7-f1f65ac9371e)

**Comment by SugarHedgehog** [comment]
- [ ] 141
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/48ca6cb6-b865-48d7-9dd1-abc0d6b7db54)

**Comment by SugarHedgehog** [comment]
- [ ] 145
https://github.com/nickkolok/chas-ege/issues/1565
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/f907227e-8592-455b-a3c0-cec74e3ca28b)

**Comment by SugarHedgehog** [comment]
- [x] 149
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/8951381d-c17a-4621-aed1-b846ec8ad6d7)

**Comment by SugarHedgehog** [comment]
- [x] 155
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/c046982a-372e-435c-bf4d-32262c6d9541)

**Comment by SugarHedgehog** [comment]
- [x] 161
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/e2524595-965b-4dd6-a8c1-b5826535d599)
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/9a5bb307-0e17-4460-840f-782680186fa3)

**Comment by SugarHedgehog** [comment]
- [x] 167
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/00579f13-d0dd-4718-9db5-fdfb8e938937)

**Comment by SugarHedgehog** [comment]
- [x] 171
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/d104c4aa-1b67-4be6-bc19-f017228ad873)

**Comment by SugarHedgehog** [comment]
- [x] 173
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/21d86406-98dd-47c7-9bd3-14887ed16cb7)

**Comment by SugarHedgehog** [comment]
- [x] 177

![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/b9094c78-fc3e-489b-9bba-5db1a320a941)

**Comment by nickkolok** [comment]
"Баклуши" искать вот тут внизу:
https://github.com/nickkolok/chas-ege/pull/1415

**Comment by nickkolok** [comment]
Актуальная версия баклуш тут:
https://github.com/nickkolok/chas-ege/pull/1415#issuecomment-1965623709

**Comment by SugarHedgehog** [comment]
Все недоделки перенесены в https://github.com/nickkolok/chas-ege/milestone/6
