### ISSUE TITLE
Векторы, одинаковые буквы

### ISSUE THREAD

**Issue by WhiteDiana** [nickkolok/chas-ege#1319]
![Снимок экрана 2023-12-18 224523](https://github.com/nickkolok/chas-ege/assets/153949399/5021ad70-e7a3-41e4-a7fc-cb509a91f694)

**Comment by SugarHedgehog** [comment]
f7c46a79e2d8c657a621a7a38fff4af9a8926f57
Было исправлено тут

**Comment by SugarHedgehog** [comment]
Можем выпустить исправленный файл хоть сейчас
