### ISSUE TITLE
Девятка про наблюдателя и горизонт

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1354]
Прототипа два. Шаблонодин. Выше 10 км наблюдатели не летают, наверное. Но это надо ещё уточнить.

![image](https://github.com/nickkolok/chas-ege/assets/5008131/3ef5989d-f68a-4656-b9ad-48ad7e76b988)

https://www.time4math.ru/_files/ugd/3fbc02_4f643ee5f7ba4d2fb3bb234ba2eab164.pdf

**Comment by Aisse-258** [comment]
шаблон создан
