### ISSUE TITLE
Исследование функции - "тригонометрический покемон"

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1414]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/ef7028a7-7766-40c7-b0af-1bf0151f888c)

Единственная из ФИПИшных, которая "точка максимума/минимума на интервале". Один шаблон. Интервал оставлять интервалом (в отрезок превращать не нужно - могут вылезти неприятности на краях. СтОит ли сдвигать границы интервала (скажем, на $2\pi$) - вопрос спорный.

**Comment by Kalendar2** [comment]
https://github.com/nickkolok/chas-ege/pull/1432
