### ISSUE TITLE
Минимакс 26708 26709

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1452]
38.3, 38.4, 39.1, 39.2.

38.1 и 38.2 к этому шаблону НЕ относятся.

![image](https://github.com/nickkolok/chas-ege/assets/5008131/55cb9c62-8497-4e44-bc21-0427d1ca6bec)

https://math-ege.sdamgia.ru/problem?id=26708
https://math-ege.sdamgia.ru/problem?id=26709

Использовать новый движок. Возможно, нужно будет сделать
```bash
git fetch origin
git checkout origin/devel
grunt build-except-ext
```
, если вылезут ошибки.

Пример использования нового движка:
https://github.com/nickkolok/chas-ege/pull/1253/files#diff-8d45e189fd061b9f173bad50fe91e0ee8b9739726f3fb7d57e87d1f1a03056f4

Движок сам делает очень много. Сам переставляет местами слагаемые, сам находит наибольшее и наименьшее значения, сам спрашивает. Задача программиста - сгенерировать ему хорошую функцию и хороший интервал - что обычно несложно. Посмотрите, насколько прост и лаконичен код образца!

**Comment by Kalendar2** [comment]
https://github.com/nickkolok/chas-ege/pull/1503

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=26704
https://math-ege.sdamgia.ru/problem?id=26709
https://math-ege.sdamgia.ru/problem?id=26708
