### ISSUE TITLE
Минимакс 36.1-38.2

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1478]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/104bfe62-0493-4bee-b2b6-ef8c3c7b89b2)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/6b63c817-f57f-4130-8fc7-df03081c1382)
![image](https://github.com/nickkolok/chas-ege/assets/5008131/3d085ed3-cbb4-4d92-8f45-c7a037594fdc)

Указание: смелее полагатесь на движок! Если Вы ему отдадите отрезок $[0;0]$, то с огромной долей вероятности (но таки проверьте!) оно выдаст ошибку, и задача уйдёт на перегенерацию. То же произойдёт, если отрезок будет плохим, и она значения (наибольшее и наименьшее) получатся не конечными десятичными дробями. Просто уйдёт на перегенерацию, потратив попытку.

Но некие ограничения всё же стОит соблюдать.

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=26704
https://math-ege.sdamgia.ru/problem?id=26707
https://math-ege.sdamgia.ru/problem?id=26706
https://math-ege.sdamgia.ru/problem?id=26702
