### ISSUE TITLE
Минимакс 33.5-33.8, 35.5-35.8

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1479]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/8ff20e21-d984-4ba0-a856-ee49de28d1a4)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/33550995-cc8f-49b6-ba2a-c01c1ed0b806)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/1f11c16a-dfae-4e29-b62e-927dfd677849)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/5f2bfa20-d7d5-4cd1-9c20-adbda07c4fd1)

Опять же, можно полагаться на движок, играться с отрезком и т.д. Задача математика-программиста - выявить то общее, что между этими задачами есть, а остальное варьировать.

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=26699
https://math-ege.sdamgia.ru/problem?id=26700
https://math-ege.sdamgia.ru/problem?id=26698

**Comment by Kalendar2** [comment]
https://github.com/nickkolok/chas-ege/pull/1549
