### ISSUE TITLE
Минимакс 33.1-33.4, 34, 35.1-35.4

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1480]
Хинт: здесь из-за ограниченности синуса и косинуса производная имеет постояныый знак.

![image](https://github.com/nickkolok/chas-ege/assets/5008131/d09b2b9b-684c-430a-95c9-0fa36eaf28b0)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/0c84294b-1904-43c9-8ca4-209bf8b86df5)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/1de84ffb-1baf-4cba-9e6c-ca1b7fc35b3b)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/3d038167-3ee0-4642-a600-787e629ad4ea)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/321d6282-ec96-4346-9da0-aeb976388685)

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=26695
https://math-ege.sdamgia.ru/problem?id=26731
https://math-ege.sdamgia.ru/problem?id=26697
https://math-ege.sdamgia.ru/test?likes=26696

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/commit/935697afefcdcf0f60505bd09448e29118d3df42
