### ISSUE TITLE
Минимакс 30

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1481]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/80ae5605-fef0-4903-87f5-5694f1bde693)

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=315127
https://math-ege.sdamgia.ru/problem?id=562980

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/commit/eaf6b5828283fc18636caf9c1724ba14e1317ba3
