### ISSUE TITLE
Минимакс 24, 25, 28, 29 (логарифмы)

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1482]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/0c856021-4ffa-4836-8448-3652c38e0cc2)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/c41d228a-9f62-4f52-a944-e7e55ec942d7)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/409fcd9c-ee89-41e9-bf14-fa671967778a)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/13cd103a-6097-4121-b5b8-e5958e74ebf4)

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=26717
https://math-ege.sdamgia.ru/problem?id=26716
https://math-ege.sdamgia.ru/problem?id=26714
https://math-ege.sdamgia.ru/problem?id=26715

**Comment by Kalendar2** [comment]
Почему-то возникает ошибка, даже когда пытаюсь запустить один пример точь в точь
```js
(function() {
	retryWhileError(function() {
		'use strict';
		let a = sl(1, 20);
		let b = sl(1, 20);
		let c = sl(1, 50);
		let l = sl(-20.5, 0, 0.5);
		let arr1 = ['+', '-'];
		let arr2 = ['1', a];
		let maxmin1 = sl1();
		let maxmin2 = (maxmin1 + 1) % 2;
		NAtask.setMinimaxFunctionTask({
			expr: '10 ln(x+9)-10 x-7',
			leftEnd: '-8.5',
			rightEnd: '0',
			primaryStep: 0.1,
			secondaryStep: 1,
			authors: ['Алендарь Сергей'],
		});
	}, 1);
})();
```

**Comment by nickkolok** [comment]
```js
(function() {
	retryWhileError(function() {
		'use strict';
		let a = sl(1, 20);
		let b = sl(1, 20);
		let c = sl(1, 50);
		let l = sl(-20.5, 0, 0.5);
		let arr1 = ['+', '-'];
		let arr2 = ['1', a];
		let maxmin1 = sl1();
		let maxmin2 = (maxmin1 + 1) % 2;
		NAtask.setMinimaxFunctionTask({
			expr: '10 log(x+9)-10 x-7',
			leftEnd: '-8.5',
			rightEnd: '0',
			primaryStep: 0.1,
			secondaryStep: 1,
			authors: ['Алендарь Сергей'],
		});
	}, 1);
})();
```
`ln` меняется на `log`. И всё начинает работать. А в ответе всё равно `ln`, потому что разные обозначения...

**Comment by Kalendar2** [comment]
https://github.com/nickkolok/chas-ege/pull/1605
