### ISSUE TITLE
Минимакс 16-17 (дроби)

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1484]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/7e769f9e-1a10-4276-a5b2-3f79dc830826)

**Comment by Kalendar2** [comment]
```js
(function() {
	retryWhileError(function() {
		'use strict';
		let a = sl(3, 30) ^ 2;
		let d = sl(-15, 15);
		let e = d + sl(3, 30);
		NAtask.setMinimaxFunctionTask({
			expr: '' + 'x^2+' + a + '/x',
			leftEnd: '' + d,
			rightEnd: '' + e,
			primaryStep: 0.001,
			authors: ['Алендарь Сергей'],
		});
	}, 1000);
})();
```

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=77469
https://math-ege.sdamgia.ru/problem?id=77470

**Comment by nickkolok** [comment]
> `a = sl(3, 30) ^ 2;`

Оператор `^` непосредственно в javascript отвечает за побитовый `XOR`, а возведение в степень выполняет только внутри `mathjs`. А непосредственно в javascript возведение в степень пишется как `**`.

>`'' + 'x^2+' + a + '/x'`

Зачем прибавлять пустую строку? И не нужны ли часом скобки?

> `primaryStep: 0.001`
Но ведь ответ всегда целый, разве нет? Зачем искать его с шагом `0.001`, если можно с шагом `1` ?

**Comment by nickkolok** [comment]
```js
(function() {
	retryWhileError(function() {
		'use strict';
		let a = sl(3, 30) ** 2;
		let d = sl(-15, 15);
		let e = d + sl(3, 30);
		NAtask.setMinimaxFunctionTask({
			expr: '' + '(x^2+' + a + ')/x',
			leftEnd: '' + d,
			rightEnd: '' + e,
			primaryStep: 1,
			authors: ['Алендарь Сергей'],
		});
	}, 10);
})();
```
