### ISSUE TITLE
Минимакс 12.3-12.4, 13.7-13.8 (произведение двучлена на экспоненту)

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1485]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/0b8daca1-f2d5-4e67-bee9-06cae2092b1c)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/10ba6aeb-672b-4e60-91ea-73dee9db91ab)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/69c6dc23-2399-483b-a842-eaf1c3f07014)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/076506b5-3d81-4aaa-9715-52fb1b9316ae)

**Comment by Kalendar2** [comment]
```js
(function() {
	retryWhileError(function() {
		'use strict';
		let a = sl(1, 3);
		let b = sl(1, 50);
		let c = sl(1, 15);
		let d = sl(-15, 15);
		let e = c + sl(3, 30);
		let arr1 = ['+', '-'];
		let arr2 = ['-', '+'];
		let maxmin = sl1();
		NAtask.setMinimaxFunctionTask({
			expr: '' + '(' + a + 'x' + arr1[sl1()] + b + ')' + 'e^(' + arr1[maxmin] + 'x' + arr2[sl1()] + c + ')',
			leftEnd: '' + d,
			rightEnd: '' + e,
			authors: ['Алендарь Сергей'],
		});
	}, 10000);
})();
```

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=26691
https://math-ege.sdamgia.ru/problem?id=130251

**Comment by nickkolok** [comment]
`primaryStep: 1/6,`
А ответ что, так всегда и 0? И, кстати, номер в конце шаблона не проставлен.

**Comment by nickkolok** [comment]
Но вообще, конечно, со скоростью движка надо что-то делать. В принципе я представляю, что. Но пока так!

**Comment by Kalendar2** [comment]
Мне кажется в производной ошшибка, там не должно быть ln(e)

**Comment by nickkolok** [comment]
Он равен единице, так что не ошибка...
