### ISSUE TITLE
Минимакс 12.1-12.2, 13.1-13.6 (произведение трёхчлена на экспоненту)

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1486]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/d878d3b7-3485-4d22-9edf-d7aacd0fe785)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/48530035-9d94-4854-be45-3b4c45132376)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/01a9892a-6b39-4779-a916-885d482dfd0a)

![image](https://github.com/nickkolok/chas-ege/assets/5008131/7d39ce8d-03e8-4b25-8b33-d2b9da4d5a66)

**Comment by Kalendar2** [comment]
```js
(function() {
	retryWhileError(function() {
		'use strict';
		let a = sl(1, 3);
		let b = sl(1, 50);
		let c = sl(1, 15);
		let d = sl(1, 15);
		let e = c + sl(3, 30);
		let arr1 = ['+', '-'];
		let arr2 = ['-', '+'];
		let arr3 = ['-', ''];
		let maxmin = sl1();
		NAtask.setMinimaxFunctionTask({
			expr: '' + '(' + a + 'x^2' + arr1[maxmin] + b + 'x' + arr2[maxmin] + b + ')' +
				'e^(' + arr3[maxmin] + 'x' + [arr1[maxmin] + c, ''].iz() + ')',
			leftEnd: '' + d,
			rightEnd: '' + e,
			authors: ['Алендарь Сергей'],
		});
	}, 10000);
})();
```

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=77479
https://math-ege.sdamgia.ru/problem?id=77480

**Comment by nickkolok** [comment]
```js

(function() {
	retryWhileError(function() {
		'use strict';
		let a = sl(1, 3);
		let b = sl(1, 50);
		let c = sl(1, 15);
		let d = sl(1, 15);
		let e = c + sl(3, 30);
		let arr1 = ['+', '-'];
		let arr2 = ['-', '+'];
		let arr3 = ['-', ''];
		let maxmin = sl1();
		NAtask.setMinimaxFunctionTask({
			expr: '' + '(' + a + 'x^2' + arr1[maxmin] + b + 'x' + arr2[maxmin] + b + ')' +
				'e^(' + arr3[maxmin] + 'x' + [arr1[maxmin] + c, ''].iz() + ')',
			leftEnd: '' + d,
			rightEnd: '' + e,
			primaryStep: 1,
			secondaryStep: 0.01,
			authors: ['Алендарь Сергей'],
		});
	}, 20);
})();

```


Мораль та же: если отрезок большой, а ответ заведомо целый - то руками выставлять `primaryStep` b `secondaryStep`. Это первый и второй шаги перебора иксов. Сначала оно проходит весь отрезок с шагом `primaryStep`, потом вокруг найденной точки - с шагом `secondaryStep`.

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/commit/1788c40aa1b337914b13d098d93dbb1dd39b88ec
