### ISSUE TITLE
Минимакс 6-7 ( x^1.5 )

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1488]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/0dd1db2c-c19e-4d83-86a9-4c9dadc06f7b)

Дополнительное указание: варьировать случайным образом запись: $x\sqrt{x}$ или $x^{3/2}$

**Comment by Kalendar2** [comment]
```js
(function() {
	retryWhileError(function() {
		'use strict';
		let a = sl(1, 30);
		let b = sl(1, 30);
		let c = sl(1, 15);
		let d = c + sl(3, 30);
		let arr1 = ['+', '-'];
		let arr2 = ['-', '+'];
		let maxmin = sl1();
		NAtask.setMinimaxFunctionTask({
			expr: '' + a + arr1[maxmin] + b + ' x ' + arr2[maxmin] + [' x sqrt(x) ','x^(3/2)'].iz(),
			leftEnd: '' + c,
			rightEnd: '' + d,
			authors: ['Алендарь Сергей'],
		});
	}, 100);
})();
//128127
```

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=77466
https://math-ege.sdamgia.ru/problem?id=77460
https://math-ege.sdamgia.ru/problem?id=129537

**Comment by nickkolok** [comment]
Оно живое...
![image](https://github.com/nickkolok/chas-ege/assets/5008131/eb446ec9-c3fd-4cea-bf76-5764ea5ec845)
Вопрос тот же. Может ли быть экстремум в нецелой точке?
