### ISSUE TITLE
Минимакс 3.4-4 (кубические)

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1489]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/9d502c01-44d9-4154-915f-53c12cc30974)
![image](https://github.com/nickkolok/chas-ege/assets/5008131/5fb9adf0-41aa-4d09-81c5-8199f02cf203)
![image](https://github.com/nickkolok/chas-ege/assets/5008131/8fe9d81a-da71-4d94-b7d6-1f70663c3a65)
![image](https://github.com/nickkolok/chas-ege/assets/5008131/e35b79d0-956f-44d3-9838-baffd06b509c)

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=77438
https://math-ege.sdamgia.ru/problem?id=77429

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/commit/7aaec47b50c84e4a74424cabae7ed49aeb8771bb
https://github.com/nickkolok/chas-ege/commit/087423c21ebf8c64a4bf282b25543f7252d9d579
