### ISSUE TITLE
Задачи про движение протяжённых тел

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1495]
На будущее.

https://infourok.ru/zadachi-na-dvizhenie-dvizhenie-protyazhennyh-tel-4763847.html
https://dzen.ru/a/YI5yQ6ONIV1OIIcC
https://ege-study.ru/zadachi-na-dvizhenie-protyazhennyx-tel-i-slozhenie-skorostej/

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/pull/1511
