### ISSUE TITLE
Падежи в .toChMin()

### ISSUE THREAD

**Issue by Aisse-258** [nickkolok/chas-ege#1518]
![Снимок экрана от 2024-03-20 22-22-33](https://github.com/nickkolok/chas-ege/assets/50519492/d0252c31-7c12-4a12-a404-94b155bd8374)

**Comment by Aisse-258** [comment]
![изображение](https://github.com/nickkolok/chas-ege/assets/50519492/eac05437-a2d4-4371-88aa-7db3bbe80a35)

**Comment by nickkolok** [comment]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/12b31a8c-9fcf-4fca-b93d-1ec01afcf51b)
