### ISSUE TITLE
Минимакс 3.1-3.3 (пятая степень, первообразные от биквадратных)

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1530]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/9d502c01-44d9-4154-915f-53c12cc30974)
![image](https://github.com/nickkolok/chas-ege/assets/5008131/3327d64f-0395-4347-8ec7-5cf0ca724843)

Про наименьшее значение, разумеется, тоже спрашивать.

**Comment by Kalendar2** [comment]
https://math-ege.sdamgia.ru/problem?id=315835
https://math-ege.sdamgia.ru/problem?id=315128
https://math-ege.sdamgia.ru/problem?id=628748

**Comment by Kalendar2** [comment]
https://github.com/nickkolok/chas-ege/pull/1554#event-13080699689
