### ISSUE TITLE
Новые двенашки (точки экстремума без отрезка) к `main.js`  и `fipi.js` подключить

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1532]
https://github.com/nickkolok/chas-ege/pull/1464

**Comment by nickkolok** [comment]
Ага, проблема вот тут:
https://github.com/nickkolok/chas-ege/pull/1432
Они подключены не туда :(

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/pull/1610
