### ISSUE TITLE
Уравнение ОГЭ 09 №2

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1543]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/a2b422f8-fe3c-44ca-a855-a0cb98078b2c)

https://www.time4math.ru/_files/ugd/3fbc02_ffb8e5a6cb13459fb21ef6fb3fb887ff.pdf

Прошу обратить внимание на функции `setEquationTask` и `setAdditiveEquationTask`, а также на функции `texfrac` и `texrndfrac`. 

Код нужно разместить комментарием здесь же, взяв его в

\`\`\`js
здесь
код
\`\`\`

(гуглить github markdown про язык разметки).

Напоминаю рекомендацию взять за основу какой-то из готовых шаблонов и переделывать его. Шаблон должен содержать в себе все приведённые уравнения как частные случаи (т.е. должны существовать такие результаты рандома, при которых они выпадут), а также, понятно, и десятки (а то и сотни) других.

**Comment by VeronikaKit** [comment]
'''js
(function(){'use strict';
var a=sluchch(1,12).pm();
var b=sluchch(1,50).pm();
var c=sluchch(1,11).pm();
chas2.task.setEquationTask({
	parts: ['x+' + '\\frac{x}{'+a+'}', '\\frac{'+b+'}{'+c+'}'],
    roots: (a*b/(c*a+c)),
 	enablePartsSubtraction: 1,
});
})();
'''

**Comment by VeronikaKit** [comment]
'''js
(function(){'use strict';
var a=sluchch(1,12).pm();
var b=sluchch(1,50).pm();
var c=sluchch(1,11).pm();
chas2.task.setEquationTask({
	parts: ['x+' + (1).texfrac(a,'x'), b.texfrac(c)],
    roots: (a*b/(c*a+c)),
 	enablePartsSubtraction: 1,
});
})();
'''

**Comment by VeronikaKit** [comment]
```js
(function(){'use strict';
var a=sluchch(1,12).pm();
var b=sluchch(1,50).pm();
var c=sluchch(1,11).pm();
chas2.task.setEquationTask({
parts: ['x+' + (1).texfrac(a,'x'), b.texfrac(c)],
roots: (a*b/(c*a+c)),
enablePartsSubtraction: 1,
});
})();
```

**Comment by VeronikaKit** [comment]
```js
(function(){'use strict';
var a=sluchch(1,12).pm();
var b=sluchch(1,50).pm();
var c=sluchch(1,11).pm();
chas2.task.setEquationTask({
	parts: ['x+' + (1).texfrac(a,'x'), b.texfrac(c)],
    roots: (a*b/(c*a+c)),
 	enablePartsSubtraction: 1,
});
})();
```

**Comment by nickkolok** [comment]
Упс!
![image](https://github.com/nickkolok/chas-ege/assets/5008131/d5281e5c-1a12-4977-bb45-4ee5446e23ac)

Всё, поскольку есть комментарий, теперь следующая версия - не редактированием, а новым сообщением. Дополнительно подумать:

а) Можно ли как-нибудь извернуться и привязать генерацию `b` к генерации `a` и `c` так, чтобы ответ был всегда конечной десятичной дробью (не обязательно вот прям целый, но не больше трёх знаков после запятой, например)?

б) Если внимательно посмотреть на задачку https://github.com/nickkolok/chas-ege/pull/1520/files , то можно увидеть, <s>как задачка внимательно смотрит на Вас</s>  что первая и последняя содержательные строки у неё немного отличаются. А если присмотреться ещё, то можно найти, где там ставится декларативное условие на тему дробности. Подсказка: ответ придётся вынести в переменную. Вот с последнего и стОит начать, пожалуй. А потом уже можно поиграться с первой и последней строками и проверкой на "неоченьдробность".

**Comment by VeronikaKit** [comment]
```js
(function(){'use strict';
var e=0;
var a, b, c, d;
while (e===0){
    a=sluchch(1,12).pm();
    b=sluchch(1,50).pm();
    c=sluchch(1, a/3, a).pm();
    d=a*b/(c*a+c);
    if (d%1===0){
        e=1;
        chas2.task.setEquationTask({
        	parts: ['x+' + (1).texfrac(a,'x'), b.texfrac(c)],
    	        roots: d,
 	        enablePartsSubtraction: 1,
        });	
        }
    else if (d%1!=0){
    	e=0;
    }
}   
})();
```

**Comment by nickkolok** [comment]
Что ж, это явно успех! Есть, конечно, несколько замечаний, но они все достаточно частные. В первую очередь, следует иметь в виду, что при вычитании частей уравнения движок не ставит скобки. Получается вот такое вот:
![image](https://github.com/nickkolok/chas-ege/assets/5008131/02963526-db8e-405f-9840-407292fb3faf)
Обойти это можно двумя способами: или установить `enablePartsSubtraction` в значение `false` (или `0`, что то же самое), или же, что предпочтительнее, использовать `setAdditiveEquationTask`, который принимает массив слагаемых для левой части произвольной длины, а потом часть из этих слагаемых переносит в правую (пример есть).
(продолжение следует)

**Comment by nickkolok** [comment]
(обещанное продолжение)
Конструкция 
```js
    if (d%1===0){
        e=1;
        chas2.task.setEquationTask({
        	parts: ['x+' + (1).texfrac(a,'x'), b.texfrac(c)],
    	        roots: d,
 	        enablePartsSubtraction: 1,
        });	
        }
    else if (d%1!=0){
    	e=0;
    }
```
избыточна аж в двух местах.

Во-первых, избыточен второй `if`, который повторяет услвоие первого, но с отрицанием. Избыточен он потом, что находится в блоке `else` первого `if`, т.е. отрицание первого условия в этом месте всегда выполнено. Как-то так. Если непонятно - прошу переспросить.

Во-вторых, избыточно присваивание `e=0` в этом блоке, посколько `e` и так равно нулю, пока его значение где-либо не поменяют. Нет необходимости присваивать его каждый раз.

Кстати, а что Вы хотели сказать выражением `sluchch(1, a/3, a)` ?

**Comment by nickkolok** [comment]
Так вот, в целом примерно по тому же принципу работает конструкция с `retryWhileError()`. Сама функция `retryWhileError()` (первый параметр этой функции - тоже функция (да, в JS так можно!), второй - количество попыток) сооветствует циклу `while`, а вот за проверку на всякий условия отвечают функции `genAssert*` (звёздочка здесь обозначает произвольный набор символов, как в маске файла - так принято).

Попробуете переписать с помощью этой конструкции?)

**Comment by nickkolok** [comment]
Если переписать через `retryWhileError()` и `genAssert*`, то получится вот что:

```js
(function() { retryWhileError(function() {
	var a, b, c, d;
    a=sluchch(1,12).pm();
    b=sluchch(1,50).pm();
    c=sluchch(1, a/3, a).pm();
    d=a*b/(c*a+c);
    genAssertZ1000(d, 'Корень не должн быть слишком дробным');
    
    chas2.task.setEquationTask({
    	parts: ['x+' + (1).texfrac(a,'x'), b.texfrac(c)],
	        roots: d,
         enablePartsSubtraction: 1,
    });	

}, 20);})();
```

Это - пример, как надо действовать. Но двух других замечаний выше это не снимает.

**Comment by VeronikaKit** [comment]
'''js

(function(){'use strict';
var e=0;
var a, b, c, d;
while (e===0){
    a=sluchch(1,12).pm();
    b=sluchch(1,50).pm();
    c=sluchch(1,50).pm();
    d=a*b/(c*a+c);
    if (d%1===0){
        e=1;
        chas2.task.setEquationTask({
        	parts: ['x+' + (1).texfrac(a,'x'), b.texfrac(c)],
    	     roots: d,
 	        enablePartsSubtraction: 1,
        });	
        }
    else if (d%1!=0){
    	e=0;
    }
}   
})();

'''

**Comment by VeronikaKit** [comment]
```js
(function(){'use strict';
var e=0;
var a, b, c, d;
while (e===0){
    a=sluchch(1,12).pm();
    b=sluchch(1,50).pm();
    c=sluchch(1,50).pm();
    d=a*b/(c*a+c);
    if (d%1===0){
        e=1;
        chas2.task.setEquationTask({
        	parts: ['x+' + (1).texfrac(a,'x'), b.texfrac(c)],
    	        roots: d,
 	        enablePartsSubtraction: 1,
        });	
        }
    else if (d%1!=0){
    	e=0;
    }
}   
})();
```

**Comment by nickkolok** [comment]
Так-так, а зачем Вы опять убрали `retryWhileError` ? Я же выше привёл вариант с ним, от этого варианта и отталкивайтесь.

**Comment by VeronikaKit** [comment]
я не увидела, извиняюсь

**Comment by VeronikaKit** [comment]
Что это за значение 20 в конце?

**Comment by nickkolok** [comment]
А в документаци не рассказывается, что делает функция `retryWhileError` ? Возможно, в том курсаче, которые про графики.

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
	var a, b, c, d;
    a=sluchch(1,12).pm();
    b=sluchch(1,50).pm();
    c=sluchch(1,50).pm();
    d=a*b/(c*a+c);
    genAssertZ1000(d, 'Корень не должн быть слишком дробным');
    
    chas2.task.setEquationTask({
    	    parts: ['x+' + (1).texfrac(a,'x'), b.texfrac(c)],
	    roots: d,
    });	

}, 20);})();
```

**Comment by nickkolok** [comment]
Так, уже почти совсем хорошо!
20 в конце я рекомендую увеличить хоть бы до 200, а может, и до 1000. (Кстати, а что это такое и как оно работает?) И нежелательно, чтобы выскакивало вот такое:
![image](https://github.com/nickkolok/chas-ege/assets/5008131/39838e66-0a8a-424b-812f-0ab49f6f3057)

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
    var a, b, c, d;
    a=sluchch(2,12).pm();
    b=sluchch(1,50).pm();
    c=sluchch(1,50).pm();
    d=a*b/(c*a+c);
    genAssertZ1000(d, 'Корень не должн быть слишком дробным');
    
    chas2.task.setEquationTask({
    	    parts: ['x+' + (1).texfrac(a,'x'), b.texfrac(c)],
	    roots: d,
    });	

}, 1000);})();
```

**Comment by nickkolok** [comment]
```js
(function() { retryWhileError(function() {
    var a, b, c, d;
    a=sluchch(2,12).pm();
    b=sluchch(1,50).pm();
    c=sluchch(1,50).pm();
    d=a*b/(c*a+c);
    genAssertZ1000(d, 'Корень не должен содержать больше трёх знаков после запятой');
    
    chas2.task.setEquationTask({
    	    parts: ['x+' + (1).texfrac(a,'x'), b.texrndfrac(c)],
	    roots: d,
    });	

}, 1000);})();
```

Рубрика "Найдите два отличия" :)

@SugarHedgehog , прошу посмотреть и высказать свой мнение (провести ревью).

**Comment by SugarHedgehog** [comment]
1) `chas2.task`--->`NAtask`, давайте не таскать старое....
2) `let` более уместно, мне кажется, но дело вкуса (Наверное?)
3) А почему такие цифорки маленькие, ну хотя бы до 50 рандом)

**Comment by nickkolok** [comment]
3) Так тут и есть до 50, не?

**Comment by nickkolok** [comment]
2) `let` считается современнее. Но когда начинался ЧАС-ЕГЭ, его ещё не изобрели. Кстати, советую @VeronikaKit почитать, чем `var`отличается от `let`. И, более того, очень советую по возможности объявлять переменную прямо в строке, где она инициализируется:
```js
    let a=sluchch(2,12).pm();
    let b=sluchch(1,50).pm();
```
Так код становится более понятным: явно показывается, что переменная именно что инициализируется, то есть обхъявляется и сразу чему-то приравнивается.

**Comment by nickkolok** [comment]
1) Строго говоря, неприемлемым считается только смешивать в одном шаблоне `NAtask` и `chas2.task` (это, грубо говоря, синонимы). Но первое и впрямь короче.

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
    let a=sluchch(2,50).pm();
    let b=sluchch(1,50).pm();
    let c=sluchch(1,50).pm();
    let d=a*b/(c*a+c);
    genAssertZ1000(d, 'Корень не должен содержать больше трёх знаков после запятой');
    
    NAtask.setEquationTask({
    	    parts: ['x+' + (1).texfrac(a,'x'), b.texrndfrac(c)],
	    roots: d,
    });	

}, 1000);})();
```

**Comment by nickkolok** [comment]
@SugarHedgehog , прошу закоммитить!

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/pull/1568
