### ISSUE TITLE
Нарезка уравнений

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#1564]
Из файла:
https://www.time4math.ru/_files/ugd/3fbc02_ffb8e5a6cb13459fb21ef6fb3fb887ff.pdf
выделить первые четыре шаблона, которые ещё не сделаны. Открыть issues по образцу #1543 #1546 #1561 . Не забыть про labels. Сослаться на эти новые issues  в комментариях к этому. Изучить каталог https://math.vsu.ru/chas-ege/sh/katalog.html и пометить, для каких шаблонов уже есть похожие. Найти эти похожие на гитхабе и выяснить, имеет ли смысл их переделывать или проще написать новые. 

Далее дождаться моего одобрения и затем приступать к программированию. Если корней несколько, то в качестве `roots` отдать массив, движок сам разберётся.

Это, если что, будет частью задания на 29 апреля.

**Comment by VeronikaKit** [comment]
1
```js
(function() { retryWhileError(function() {
    let a=sluchch(1,50).pm();
    let b=sluchch(1,50).pm();
    let c=sluchch(1,50).pm();
    let d=(c-a*b)/a;
    genAssertZ1000(d, 'Корень не должен быть слишком дробным');
    
    NAtask.setEquationTask({
    	    parts: [a+'(x+' + b + ')', c],
	    roots: d,
    });	

}, 20);})();
```

**Comment by VeronikaKit** [comment]
![задание](https://github.com/nickkolok/chas-ege/assets/166473321/255f87db-12df-4ef6-a458-0f08ce7b63f5)

**Comment by nickkolok** [comment]
Этот код - что и куда? Тут кода вообще как бы не предполагается, только ссылки на открытые отдельные issues и, быть может, какое-то обсуждение. Раз уж мы его обсудили - не удаляйте, но впредь код прошу постить в соотвествующие суйни :)

**Comment by VeronikaKit** [comment]
#1572

**Comment by VeronikaKit** [comment]
#1567

**Comment by VeronikaKit** [comment]
[chas-ege](https://github.com/nickkolok/chas-ege/tree/429d3303bf5f6faddb65529d7ed7e6deed1833c8)/[zdn](https://github.com/nickkolok/chas-ege/tree/429d3303bf5f6faddb65529d7ed7e6deed1833c8/zdn)/[mat2014](https://github.com/nickkolok/chas-ege/tree/429d3303bf5f6faddb65529d7ed7e6deed1833c8/zdn/mat2014)/[B7](https://github.com/nickkolok/chas-ege/tree/429d3303bf5f6faddb65529d7ed7e6deed1833c8/zdn/mat2014/B7)
/77368.js

**Comment by VeronikaKit** [comment]
#1573

**Comment by VeronikaKit** [comment]
zdn/mat2014/B7/77368.js

**Comment by VeronikaKit** [comment]
[[zdn][new] 77368 - a rational equation by Belozorov](https://github.com/nickkolok/chas-ege/commit/dda49556cafa5a25ade2a819c760d73e4f3c0b76)

**Comment by nickkolok** [comment]
> [[zdn][new] 77368 - a rational equation by Belozorov](https://github.com/nickkolok/chas-ege/commit/dda49556cafa5a25ade2a819c760d73e4f3c0b76)

Ага! Согласен, действительно похож. Но есть и различия. 
![image](https://github.com/nickkolok/chas-ege/assets/5008131/79e028aa-fc46-41e1-84ea-5d392f77e36c)
![image](https://github.com/nickkolok/chas-ege/assets/5008131/fc883094-d34f-4efd-9740-f74dd69f34a6)

В том, что есть, перед иксм коэффициент бывает, а икс вторым слагаемым - не бывает. А у нас - наоборот. Попробуйте модифицировать существующий шаблон, пожалуйста. И суйню откройте, да.

**Comment by nickkolok** [comment]
На 6 мая: проделать то же до задания №7 блока 1 включительно :)

**Comment by VeronikaKit** [comment]
#1574

**Comment by nickkolok** [comment]
На следующую неделю: проделать то же до задания №11 блока 1 включительно, т.е. весь первый блок :)
