### ISSUE TITLE
Уравнение ОГЭ 09 №1.13-1.18

### ISSUE THREAD

**Issue by VeronikaKit** [nickkolok/chas-ege#1567]
![image](https://github.com/nickkolok/chas-ege/assets/166473321/a2c5a256-4ca6-4ce4-91b7-9e3b75a3e543)
![2024-04-29 174841](https://github.com/nickkolok/chas-ege/assets/166473321/a1eabab6-b361-4b0d-b180-67097c101c02)

```js
(function() { retryWhileError(function() {
    let a=sluchch(1,50).pm();
    let b=sluchch(1,50).pm();
    let c=sluchch(1,50).pm();
    let d=c/a-b;
    genAssertZ1000(d, 'Корень не должен быть слишком дробным');
    
    NAtask.setEquationTask({
    	    parts: [a+'(x+' + b + ')', c],
	    roots: d,
    });	

}, 20);})();
```

**Comment by nickkolok** [comment]
В первом посте не хватает скрина формулировки задания и номера.

**Comment by nickkolok** [comment]
`d=(c-a*b)/a;` - а нельзя ли эту формулу как-то упростить?

**Comment by VeronikaKit** [comment]
готово

**Comment by nickkolok** [comment]
Ещё раз повторяю: если код уже прокомментирован, то не надо его исправлять "задним числом", логика теряется. Просто кидаете снизу новый.

Это всё, конечно, костыль. Для того, чтобы этих костылей не было, и нужен git. Но мы пока до него не дошли :(

**Comment by nickkolok** [comment]
@SugarHedgehog , ревью!)

**Comment by SugarHedgehog** [comment]
Всё прекрасно

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/pull/1621
