### ISSUE TITLE
Уравнение ОГЭ 09 №3.1-3.12

### ISSUE THREAD

**Issue by VeronikaKit** [nickkolok/chas-ege#1572]
![image](https://github.com/nickkolok/chas-ege/assets/166473321/0bccd205-c5d0-494f-9e40-5d5e7a5fc57c)
```js
(function() { retryWhileError(function() {
    let a=sluchch(1,50).pm();
    let b=sluchch(1,50).pm();
    let c=sluchch(1,30).pm();
    let e=sluchch(1,50).pm();
    let d=(e*a-b*c)/c;
    genAssertZ1000(d, 'Корень не должен быть слишком дробным');
    genAssert(d!=-b, 'По условию');
    NAtask.setEquationTask({
    	    parts: ['\\frac{'+a+'}{'+'x+'+b+'}', c.texfrac(e)],
	    roots: d,
    });	

}, 20);})();
```

**Comment by nickkolok** [comment]
@SugarHedgehog , прошу ревью.
@VeronikaKit , маленькое замечание к заголовку: если issue не на весь номер, а только на его кусок, то просьба это отражать.
![image](https://github.com/nickkolok/chas-ege/assets/5008131/966b7fd4-94d5-4d0a-8207-8d2eeddf620c)

**Comment by SugarHedgehog** [comment]
А почему бы не добавить перед `x` коэффициент тоже?
Хотя бы +-1

**Comment by VeronikaKit** [comment]
и как это сделать?

**Comment by nickkolok** [comment]
@SugarHedgehog , а вот здесь не соглашусь. Всё-таки это ОГЭ, и лишние коэффициенты, слагаемые и т.д. тут могут начать отвлекать. Ещё замечания?

**Comment by SugarHedgehog** [comment]
Тогда всё в порядке

**Comment by SugarHedgehog** [comment]
> и как это сделать?

Например, так
`parts: ['\\frac{'+a+'}{'+[1,-1].iz()+'x+'+b+'}', c.texfrac(e)],`

Или

`parts: ['\\frac{'+a+'}{'+'-'.esli(sl1())+'x+'+b+'}', c.texfrac(e)],`

**Comment by nickkolok** [comment]
Ага, спасибо, @SugarHedgehog . Как я понимаю, можно принимать?

**Comment by SugarHedgehog** [comment]
> Ага, спасибо, @SugarHedgehog . Как я понимаю, можно принимать?

Да

**Comment by nickkolok** [comment]
Тогда проошу принимать...

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/pull/1622
