### ISSUE TITLE
Уравнение ОГЭ 09 №4, №6

### ISSUE THREAD

**Issue by VeronikaKit** [nickkolok/chas-ege#1573]
![2024-04-29 174540](https://github.com/nickkolok/chas-ege/assets/166473321/f3217946-9cc3-4362-a745-2a12a0aa5a39)
![image](https://github.com/nickkolok/chas-ege/assets/166473321/fa24d72e-5624-4aae-94ea-428919771f0b)

```js
(function() { retryWhileError(function() {
    let a=sluchch(1,50).pm();
    let b=sluchch(1,50).pm();
    let c=sluchch(1,50).pm();
    let e=sluchch(1,50).pm();
    let d=Math.min(-b/a, -e/c);
    genAssertZ1000(d, 'Корень не должен быть слишком дробным');
    NAtask.setEquationTask({
    	        parts: ['('+a+'x+'+b+')('+c+'x+'+e+')', '0'],
	        roots: d,
	
    });	

}, 20);})();
```

**Comment by nickkolok** [comment]
```js
    if (z>r){
    	d=r;
    }
    else if (r>z){
    	d=z;
    }
    else if (r===z){
    	d=r;
    }
```
Во-первых, это можно записать короче: с одним ифом, тернарным оператором или вовсе через `Math.min()`.
Во-вторых, цитата из #1564 :

> Если корней несколько, то в качестве `roots` отдать массив, движок сам разберётся.

И уж совершенно незачем писать часть условия в консоль, оно там пропадёт, его никто не увидит... Консоль - это такой черновик для логов и отладки.

Движок (встроенные библиотеки) мы стараемся сделать настолько умными и продвинутыми, насколько возможно. Это в принципе разумная стратегия для любого долгоживущего проекта... А ЧАС-ЕГЭ через недельку 11 лет стукнет. Если чего-то в библиотеках нет, то, конечно, можно и костыликом подпереть, но обычно при этом как-то ставится вопрос о добавлении в библиотеку. Если что: возможности решать уравнения автоматически пока нет.

**Comment by nickkolok** [comment]
Кроме того, иногда вылезает вот такое вот:
![image](https://github.com/nickkolok/chas-ege/assets/5008131/521d3c41-650d-4a99-a7f2-80bdf9cd7e91)

**Comment by VeronikaKit** [comment]
тут тоже готово было, просто забыла сказать

**Comment by nickkolok** [comment]
Ещё один аргумент в пользу того, чтобы писать новые сообщения, а не редактировать старые: о редактировании не приходит уведомлений.

**Comment by nickkolok** [comment]
Не, с несколькими корнями - не так. Про `Math.min` я рассказал исключительно в познавательных целях, а сейчас нужно в качестве `roots` отдать массив изо всех корней. А движок уже сам разьерётся, какой спрашивать.

**Comment by VeronikaKit** [comment]
это как?
можно пример

**Comment by nickkolok** [comment]
Можно, конечно. Разве в каталоге нет?

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
    let a=sluchch(1,50).pm();
    let b=sluchch(1,50).pm();
    let c=sluchch(1,50).pm();
    let e=sluchch(1,50).pm();
    let d=-b/a;
    let z=-e/c;
    genAssertZ1000(d+z, 'Сумма корней не должна быть слишком дробной');
    genAssertZ1000(d, 'Корень не должен быть слишком дробным');
    genAssertZ1000(z, 'Корень не должен быть слишком дробным');
    NAtask.setEquationTask({
    	            parts: ['('+a+'x+'+b+')('+c+'x+'+e+')', '0'],
	            roots: [d,z],
	         handleMultipleRoots: 'randomExceptList',
	
    });	

}, 20);})();
```

**Comment by nickkolok** [comment]
Во-первых, отступы.
Во-вторых, а почему так странно именуются переменные? `a`, `b`, `c`, `d`, `e`... `z`?
В-третьих, а почему "Сумма корней не должна быть слишком дробной"? Вы ведь, вероятно, что-то имели в виду, предусматривая эту проверку?..

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
    let a=sluchch(1,50).pm();
    let b=sluchch(1,50).pm();
    let c=sluchch(1,50).pm();
    let e=sluchch(1,50).pm();
    let d=-b/a;
    let z=-e/c;
    genAssertZ1000(d+z, 'Сумма корней не должна быть слишком дробной');
    genAssertZ1000(d, 'Корень не должен быть слишком дробным');
    genAssertZ1000(z, 'Корень не должен быть слишком дробным');
    NAtask.setEquationTask({
    	    parts: ['('+a+'x+'+b+')('+c+'x+'+e+')', '0'],
	    roots: [d,z],
	    handleMultipleRoots: 'randomExceptList',
	
    });	

}, 20);})();
```

**Comment by VeronikaKit** [comment]
а что не так с названием переменных, если мне так удобнее?

**Comment by nickkolok** [comment]
О, именование переменных - больная тема! Всегда и везде. И в теоретической математике тоже. Оно должно быть логичным. Уж если Вы именуете переменные по алфавиту, то так и продолжайте... Зачем перескакивать? Или уж тогда `x1` и `x2`.
Кроме того, в силе вопрос, 
> почему "Сумма корней не должна быть слишком дробной"? Вы ведь, вероятно, что-то имели в виду, предусматривая эту проверку?..

**Comment by VeronikaKit** [comment]
а, я поняла о чем вы говорите, она не нужна, корни и так проверяются и если их сложить хуже не станет

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
    let a=sluchch(1,50).pm();
    let b=sluchch(1,50).pm();
    let c=sluchch(1,50).pm();
    let d=sluchch(1,50).pm();
    let e=-b/a;
    let f=-e/c;
    genAssertZ1000(d, 'Корень не должен быть слишком дробным');
    genAssertZ1000(z, 'Корень не должен быть слишком дробным');
    NAtask.setEquationTask({
    	    parts: ['('+a+'x+'+b+')('+c+'x+'+d+')', '0'],
	    roots: [e,f],
	    handleMultipleRoots: 'randomExceptList',
	
    });	

}, 20);})();
```

**Comment by nickkolok** [comment]
Прошу на меня не сердиться, но... Вы это вообще запустить пробовали?

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
    let a=sluchch(1,50).pm();
    let b=sluchch(1,50).pm();
    let c=sluchch(1,50).pm();
    let d=sluchch(1,50).pm();
    let e=-b/a;
    let f=-e/c;
    genAssertZ1000(d, 'Корень не должен быть слишком дробным');
    genAssertZ1000(f, 'Корень не должен быть слишком дробным');
    NAtask.setEquationTask({
    	    parts: ['('+a+'x+'+b+')('+c+'x+'+d+')', '0'],
	    roots: [e,f],
	    handleMultipleRoots: 'randomExceptList',
	
    });	

}, 20);})();
```

**Comment by VeronikaKit** [comment]
в ответе забыла исправить, что бы все по порядку было

**Comment by nickkolok** [comment]
![image](https://github.com/nickkolok/chas-ege/assets/5008131/3362a252-7861-4887-b547-48306f684a92)

Иногда вот такое, а иногда нормально работает. Кажется, мы такого рода проблему уже обсуждали?..

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
    let e=sluchch(1,20).pm();
    let f=slKrome(e,1,20).pm();
    let b=sluchch(1,50).pm();
    let d=sluchch(1,50).pm();
    let c=-d/f;
    let a=-b/e;
    genAssertZ1000(c, 'По условию');
    genAssertZ1000(a, 'По условию');
    NAtask.setEquationTask({
    	    parts: ['('+a+'x+'+b+')('+c+'x+'+d+')', '0'],
	    roots: [e,f],
	    handleMultipleRoots: 'randomExceptList',
	
    });	

}, 20);})();
```

**Comment by nickkolok** [comment]
Не помогло.
![image](https://github.com/nickkolok/chas-ege/assets/5008131/af640529-d233-49c2-bebc-2d6ba0f6232d)

Это исправляется несколько иначе... Разве мы это не обсуждали?
Кстати, сообщение "По условию" - неинформативно :(

**Comment by VeronikaKit** [comment]
Как?

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
    let e=sluchch(1,20).pm();
    let f=sluchch(1,20).pm();
    let a=sluchch(1,50).pm();
    let c=sluchch(1,50).pm();
    let b=-e*a;
    let d=-f*c;
    NAtask.setEquationTask({
    	    parts: ['('+a+'x+'+b+')('+c+'x+'+d+')', '0'],
	    roots: [e,f],
	    handleMultipleRoots: 'randomExceptList',
	
    });	

}, 20);})();
```

**Comment by nickkolok** [comment]
> Как?
"А если найду?" Я, конечно, могу и ошибаться. Может оказаться, что обсуждали мы это не с Вами. Но Вам необходимо конспектировать нетривиальные вещи куда-то.
https://github.com/nickkolok/chas-ege/issues/1543#issuecomment-2061935988

**Comment by nickkolok** [comment]
Ответ-то правильный, но в оригинале корни бывают дробным, а у Вас только целые. Вы добились цеых корней именно тем способом, который для этого обычно применяется, но... нужно-то и дробные корни!

**Comment by VeronikaKit** [comment]
как отрегулировать 3 знака после запятой?

**Comment by nickkolok** [comment]
Вопрос не вполне понятен, но попробуйте умножить или разделить на 10, 100 и т.д.
Или уточните вопрос :)

**Comment by VeronikaKit** [comment]
в ответе 3 знака после запятой 1000, 20 или 100?
когда делаем проверку условия на дробность

**Comment by nickkolok** [comment]
Вопрос всё ещё неясен :(

**Comment by VeronikaKit** [comment]
}, 20);})();
20 здесь за что отвечает?

**Comment by SugarHedgehog** [comment]
> }, 20);})(); 20 здесь за что отвечает?

Это количество попыток, которое будет делать шаблон, пока не сломается и не выведет ошибки.
Если в процессе этих 20ти какой-нибудь 11тый раз окажется нормальным (выполнились все условия), то шаблон выведет задание и ответ

Каждый `genAssert` это условие, которое может отправить шаблон на новый круг

**Comment by SugarHedgehog** [comment]
Поясню, что от вас хочет @nickkolok.

1) `genAssert` должен содержать комментарий об ошибке. Например, 
`genAssertZ1000(c, 'По условию');` по хорошему должен писать  `'число c - слишком дробное'`. Если комментария не будет, то оно выведет стандартное (см. ниже)

Думаю с кодом будет понятнее

```js
function genAssertZ1000(number, message){
	genAssert((1000*number).isAlmostInteger(), message || 'Число должно иметь не более 3 знаков после запятой');
}
```
2) @nickkolok просит вас сделать ответ дробным. 
И вот этот вариант давал такие ответы, но ему просто не хватало перезапусков
https://github.com/nickkolok/chas-ege/issues/1573#issuecomment-2110836301

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
    let a=sluchch(1,20).pm();
    let b=sluchch(1,20).pm();
    let c=sluchch(1,50).pm();
    let d=sluchch(1,50).pm();
    let e=-b/a;
    let f=-d/c;
    genAssertZ1000(e, 'Корень не должен быть слишком дробным');
    genAssertZ1000(f, 'Корень не должен быть слишком дробным');
    NAtask.setEquationTask({
    	    parts: ['('+a+'x+'+b+')('+c+'x+'+d+')', '0'],
	    roots: [e,f],
	    handleMultipleRoots: 'randomExceptList',
	
    });	
}, 20);})();
```

**Comment by SugarHedgehog** [comment]
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/d33f16b2-1e1f-4d9f-a2c5-064e07259d9d)
20 раз до сих пор мало

**Comment by VeronikaKit** [comment]
```js
(function() { retryWhileError(function() {
    let a=sluchch(1,20).pm();
    let b=sluchch(1,20).pm();
    let c=sluchch(1,50).pm();
    let d=sluchch(1,50).pm();
    let e=-b/a;
    let f=-d/c;
    genAssertZ1000(e, 'Корень не должен быть слишком дробным');
    genAssertZ1000(f, 'Корень не должен быть слишком дробным');
    NAtask.setEquationTask({
    	    parts: ['('+a+'x+'+b+')('+c+'x+'+d+')', '0'],
	    roots: [e,f],
	    handleMultipleRoots: 'randomExceptList',
	
    });	
}, 100);})();

```

**Comment by SugarHedgehog** [comment]
Шаблон одобрен.

**Comment by VeronikaKit** [comment]
https://math-oge.sdamgia.ru/problem?id=369496
