### ISSUE TITLE
Уравнения 09 №6

### ISSUE THREAD

**Issue by VeronikaKit** [nickkolok/chas-ege#1579]
![image](https://github.com/nickkolok/chas-ege/assets/166473321/fa24d72e-5624-4aae-94ea-428919771f0b)
#1573

**Comment by nickkolok** [comment]
Ага! Нашли одинаковые! Это хорошо, это правильно))) А теперь смотрите, что я сделаю. Один раз это я сделаю сам, а дальше - Вы. Я отредактирую заголовок и первое сообщение #1573, а это закрою как дубликат. Да, в этом случае так можно.
