### ISSUE TITLE
Смешанная стереометрия

### ISSUE THREAD

**Issue by WhiteDiana** [nickkolok/chas-ege#1596]
здесь в номере 1 и 5 несовпадение вершин, которые даны и рисунка, 
неправильные ответы в номерах 25 и 26

**Comment by WhiteDiana** [comment]
https://vk.com/egemathika?w=wall-206799672_2573

**Comment by SugarHedgehog** [comment]
f68e52dbb888725f835145a48f7a7cf47d0ad09f
37ab80a7787996f8c98555b44d213a755f8a77eb
