### ISSUE TITLE
Баг в отображении степени или несовершенство шаблона?

### ISSUE THREAD

**Issue by SugarHedgehog** [nickkolok/chas-ege#1607]
![изображение](https://github.com/nickkolok/chas-ege/assets/88662554/59c1b7ea-5693-4fdd-b8e9-44d703ef158b)

**Comment by nickkolok** [comment]
Там со степенями логарифмов вообще большой нежданчик вылез. Оно искренне считает, что логарифм вычисляется сначала, и только потом степень.

**Comment by SugarHedgehog** [comment]
Пофикшено!
