### ISSUE TITLE
Пример 3. Решить уравнение: 5^{2x}-7^x-35*5^{2x}+35*7^x=0

### ISSUE THREAD

**Issue by wazix** [nickkolok/chas-ege#188]
http://ege-ok.ru/2013/02/14/razlozhenie-mnogochlena-na-mnozhiteli-chast-2
Пример 3. Решить уравнение: ![](http://ege-ok.ru/wp-content/plugins/wpmathpub/phpmathpublisher/img/math_993_4bf7908bff1d4742548efa282dd6c17b.png)

**Comment by nickkolok** [comment]
Такое уже есть.
