### ISSUE TITLE
Неправильно реагирует на склонение 

### ISSUE THREAD

**Issue by konan01** [nickkolok/chas-ege#194]
{vel:' сумма оставшихся углов', vin:'сумму оставшихся углов', rod:1, nah:1,  zna:o+o2}

**Comment by konan01** [comment]
http://pastebin.ru/TdVjQAbq

**Comment by nickkolok** [comment]
При отсутствии параметра rod не реагирует на vin

**Comment by nickkolok** [comment]
Бага нет, приглючилось.
