### ISSUE TITLE
Высота конуса равна 57, а диаметр основания — 152. Найдите образующую конуса.

### ISSUE THREAD

**Issue by Shellge** [nickkolok/chas-ege#400]
http://matematikalegko.ru/konus-cilindr/zadachi-s-konusami-chast-1.html
Высота конуса равна 57, а диаметр основания — 152. Найдите образующую конуса.

**Comment by nickkolok** [comment]
При написании расчётки объединить с https://github.com/nickkolok/chas-ege/issues/401
