### ISSUE TITLE
Высота конуса равна 21, а длина образующей — 75 . Найдите диаметр основания конуса.

### ISSUE THREAD

**Issue by Shellge** [nickkolok/chas-ege#401]
http://matematikalegko.ru/konus-cilindr/zadachi-s-konusami-chast-1.html
Высота конуса равна 21, а длина образующей — 75 . Найдите диаметр основания конуса.

**Comment by nickkolok** [comment]
При написании расчётки объединить с https://github.com/nickkolok/chas-ege/issues/400
