### ISSUE TITLE
 Задача про кузнечика.

### ISSUE THREAD

**Issue by hirohito-san** [nickkolok/chas-ege#73]
http://ege-ok.ru/2015/08/20/zadachi-po-kombinatorike

Есть n клеточек, расположенных последовательно. Кузнечик должен попасть из крайней левой клеточки в крайнюю правую, прыгая вправо на произвольное число клеток.

а) Сколькими способами он может это сделать?
б) сколькими способами кузнечик может добраться в n-ю клетку, сделав k шагов?
в) сколькими способами кузнечик может добраться в n-ю клетку, двигаясь на одну или на две клетки вправо?

**Comment by konan01** [comment]
начал выполнение

**Comment by konan01** [comment]
промежуточный результат 
http://pastebin.ru/npENNV8R

**Comment by konan01** [comment]
не закончена проблема в варианте Б 
http://pastebin.ru/COcBnYVB

**Comment by nickkolok** [comment]
Функции объявляются примерно так:

function factorial(n){
  if(n==0)
    return 1;
  return n*factorial(n-1);
}

**Comment by konan01** [comment]
окончательная версия 
http://pastebin.ru/3x2a0elu

**Comment by hripunov** [comment]
Всё отлично, но case здесь ни к чему - убрал и case, и лишние переменные:

http://pastebin.ru/V0JsLsop

**Comment by hripunov** [comment]
Прошу прощения, не заметил что переменная <b>a</b> уже используется. Исправил: 

http://pastebin.ru/W7jVz3l3

**Comment by nickkolok** [comment]
Строго говоря, case там вполне оправдан. При способе с массивом проводятся вычисления в **каждой** "ветке", при способе с case - только в выбранной. Поэтому несколько сложений-умножений ещё можно класть в массив, а вот вызов рекурсивной функции...

**Comment by nickkolok** [comment]
Закоммичено: https://github.com/konan01/chas-ege/commit/601bbc3c03799ca308a02c38aa8ff95aa518eb50
