### ISSUE TITLE
Неправильно склоняется "вишня"

### ISSUE THREAD

**Issue by SugarHedgehog** [nickkolok/chas-ege#754]
Имеется два джема. Первый содержит 10% вишню, второй 45% вишню.Из этих двух джемы получили третий джема массой 525 кг, содержащий 35% вишню. Найдите массу первого джема. Ответ дайте в килограммах.
```

lx['вишня']={
	ie:'вишня',
	re:'вишни',
	de:'вишне',
	ve:'вишню',
	te:'вишней',
	pe:'вишне',
	im:'вишни',
	rm:'вишен',
	dm:'вишням',
	vm:'вишни',
	tm:'вишнями',
	pm:'вишнях',
	rod:1,
	skl:1,
	odu:0,
	sbs:0,
	chr:1,
};

```

**Comment by nickkolok** [comment]
А тут точно проблема в склонении вишен и джемов, а не в выборе падежей непосредственно в коде?

**Comment by Aisse-258** [comment]
> А тут точно проблема в склонении вишен и джемов, а не в выборе падежей непосредственно в коде?

С джемами всё нормально, а вишни и правда ведут себя странно
