### ISSUE TITLE
Неправильно склоняется "ваниль"

### ISSUE THREAD

**Issue by SugarHedgehog** [nickkolok/chas-ege#755]
Имеется два крема. Первый содержит 10% ваниля, второй 30% ваниля. Из этих двух кремов получили третий крем массой 280 кг, содержащий 25% ваниля. На сколько килограммов масса первого крема была меньше массы второго?
```
lx['ваниль']={
	ie:'ваниль',
	re:'ванили',
	de:'ванили',
	ve:'ваниль',
	te:'ванилью',
	pe:'ванили',
	im:'ванили',
	rm:'ванилей',
	dm:'ванилям',
	vm:'ванили',
	tm:'ванилями',
	pm:'ванилях',
	rod:1,
	skl:1,
	odu:0,
	sbs:0,
	chr:1,
};
```

**Comment by nickkolok** [comment]
Склонение всё-таки третье)
