### ISSUE TITLE
Неправильно склоняется "Любовь"(имя)

### ISSUE THREAD

**Issue by SugarHedgehog** [nickkolok/chas-ege#765]
Вика, Надежда, Аня и Любовь учредили компанию с уставным капиталом 200000 рублей. Вика внесла 14% уставного капитала, Надежда - 42000 рублей, Аня - 0,12 уставного капитала, а оставшуюся часть капитала внесла Любовь. Учредители договорились делить ежегодную прибыль пропорционально внесенному в уставной капитал вкладу. Какая сумма от прибыли 1000000 рублей причитается Любовю? Ответ дайте в рублях.
```
lx['Любовь']={
	ie:'Любовь',
	re:'Любови',
	de:'Любови',
	ve:'Любовь',
	te:'Любовью',
	pe:'Любови',
	im:'Любови',
	rm:'Любовей',
	dm:'Любовям',
	vm:'Любови',
	tm:'Любовями',
	pm:'Любовях',
	rod:1,
	skl:3,
	odu:0,
	sbs:1,
	chr:1,
};
```

**Comment by nickkolok** [comment]
Спасибо! Пригодится, конечно. На всякий случай есть стандартный лайфхак: `sklonlxkand("Любовь3")`
