### ISSUE TITLE
Неправильно склоняется "номер"

### ISSUE THREAD

**Issue by Aisse-258** [nickkolok/chas-ege#770]
sklonlxkand('номер').im = 'номеры'
sklonlxkand('номер').vm = 'номеры'
д.б. "номера"

**Comment by nickkolok** [comment]
Огонь! Правьте :)

**Comment by Aisse-258** [comment]
похоже что оно попало в это правило
['б','в','д','з','л','м','н','п','р','с','т','ф','ц'].map(function(a){
	lxskl[a]={
		ie:a,
		re:a+'а',
		de:a+'у',
		ve:a,
		te:a+'ом',
		pe:a+'е',
		im:a+'ы',
		rm:a+'ов',
		dm:a+'ам',
		vm:a+'ы',
		tm:a+'ами',
		pm:a+'ах',
		rod:0,
		skl:2,
		odu:0,
	};
});

**Comment by nickkolok** [comment]
А со вторым склонением всегда непонятно, оно в итоге на -`ы` или на -`а`. Только руками добавлять :(
