### ISSUE TITLE
Перегнать #835 и другие пересекашки

### ISSUE THREAD

**Issue by SugarHedgehog** [nickkolok/chas-ege#840]
Дополнения к обзаду 
a*sqrt(x+b)=y ✅
sqrt(x+b)+c=y ✅

**Comment by SugarHedgehog** [comment]
(ax+b)/(x+c) kx+d ✅
k/(x+b) kx+c ✅

**Comment by SugarHedgehog** [comment]
$\frac{(k_1x+d1)}{(x+c1)}$  $\frac{(k_2x+d2)}{(x+c2)}$ ✅

**Comment by SugarHedgehog** [comment]
$a^x kx+b$✅

**Comment by SugarHedgehog** [comment]
Сложный-прикольный бред
На графике изображены графики функций: парабола и две прямые
Найти k|b|f(x0) той прямой, которая имеет точку пересечения с параболой в точке(x1,y1)

**Comment by SugarHedgehog** [comment]
Дана гипербола и прямая✅
Точки пересечения не видны на рисунке
Пусть ищут две точки пересечения
В ответ точку с меньшим/большим х/у

**Comment by SugarHedgehog** [comment]
https://math-ege.sdamgia.ru/problem?id=564555

**Comment by SugarHedgehog** [comment]
кубические параболы (4 точки или дать-таки один коэффициент) ✅ [туть](https://github.com/nickkolok/chas-ege/pull/889)

"параболы курильщика" (следить за количеством точек и додавать коэффициентов)
"пикантные вопросы о параболах" 

параболы с целым числом а в знаменателе (а-ля решуегэ) ✅[здесячки](https://github.com/nickkolok/chas-ege/pull/890)

модули а-ля Ларин ✅ [здесь](https://github.com/nickkolok/chas-ege/pull/894)

Косинусы Ларина 1✅[кошмар](https://github.com/nickkolok/chas-ege/pull/895)

Косинусы Ларина 2 ✅[кошмар номер два](https://github.com/nickkolok/chas-ege/pull/896)
модули а-ля Райский ✅[на облачках](https://github.com/nickkolok/chas-ege/pull/897)

k/(x+b)^2✅ [туточки](https://github.com/nickkolok/chas-ege/pull/891)

тригонометрия с иррациональным множителем (и, возможно, другой сеткой); опционально - указанный или неизвестный сдвиг по фазе.

парабола с модулем при среднем коэффициенте ✅[каракатится](https://github.com/nickkolok/chas-ege/pull/893)

**Comment by nickkolok** [comment]
https://prof.mathege.ru/clones/?position=184&parent=159396
Удлиннённые корни. Со сдвинутой системой координат.
![image](https://user-images.githubusercontent.com/5008131/177776878-fb416fc6-2ba8-40da-878e-0e9bb0062104.png)

**Comment by SugarHedgehog** [comment]
> 

https://github.com/nickkolok/chas-ege/pull/898

**Comment by SugarHedgehog** [comment]
> https://prof.mathege.ru/clones/?position=184&parent=159396 Удлиннённые корни. Со сдвинутой системой координат. ![image](https://user-images.githubusercontent.com/5008131/177776878-fb416fc6-2ba8-40da-878e-0e9bb0062104.png)

https://github.com/nickkolok/chas-ege/pull/898

**Comment by SugarHedgehog** [comment]
С гордостью, можно закрыть
