### ISSUE TITLE
Корень и прямая сложные (из досрочного)

### ISSUE THREAD

**Issue by nickkolok** [nickkolok/chas-ege#873]
![image](https://user-images.githubusercontent.com/5008131/160837406-95cedc87-bb9d-4c05-b4a7-ab89026f2166.png)

Если точек у прямой достаточно, то коэффициенты можно и не показывать... Или  хотя бы один их них.

Важно, вероятно, что видна точка, из которой "выходит" корень.

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/pull/1029
