### ISSUE TITLE
Баг .ts()

### ISSUE THREAD

**Issue by SugarHedgehog** [nickkolok/chas-ege#989]
![изображение](https://user-images.githubusercontent.com/88662554/215322617-9311b9e3-2cf9-4b88-84cc-221cfe11934e.png)
```js
k=0.1
'$y='+(k.ts(1)+'x+'+b.ts(1)).plusminus()+'$'
'$y='+(k.ts()+'x+'+b.ts(1)).plusminus()+'$'
```

**Comment by SugarHedgehog** [comment]
Лечится при помощи пробела 
НО неприятно
```js
k=0.1
'$y='+(k.ts(1)+' x+'+b.ts(1)).plusminus()+'$'
'$y='+(k.ts()+' x+'+b.ts(1)).plusminus()+'$'
```

**Comment by nickkolok** [comment]
Отличная наблюдательность!
Даю добро на то, чтобы `.ts(1)` (именно с 1) всегда генерила пробелы вокруг результата. В конце концов, это же латех, тут можно.

**Comment by SugarHedgehog** [comment]
https://github.com/nickkolok/chas-ege/pull/1028
